<?php require_once __DIR__.'/../../helpers/addError.php';?>
<form method="post" action="/article/<?php echo $this->form->getId(); ?>">
    <input type="hidden" name="article.id" value="<?php echo $this->form->getId(); ?>">
    <fieldset>
        <legend>New article</legend>
        <div class="form-group">
            <label>Name of article: </label>
            <input name="article.title" value="<?php echo $this->form->getTitle(); ?>"/>
            <?php showError('article.title'); ?>
        </div>
        <div class="form-group">
            <label>Content: </label>
            <textarea name="article.content" cols="60" rows="10"><?php echo $this->form->getContent(); ?></textarea>
            <?php showError('article.content'); ?>
        </div>
    </fieldset>
    <div class="form-group"><input type="submit" class="btn btn-success" value="Send" <?php if (isset($this->errors)): ?>autofocus<?php endif; ?> /></div>
</form>
