-- MySQL Script generated by MySQL Workbench
-- zo 15 feb 2015 21:31:59 CET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dutch_frontiers_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dutch_frontiers_blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dutch_frontiers_blog` ;

-- -----------------------------------------------------
-- Table `dutch_frontiers_blog`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutch_frontiers_blog`.`Users` ;

CREATE TABLE IF NOT EXISTS `dutch_frontiers_blog`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutch_frontiers_blog`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutch_frontiers_blog`.`Posts` ;

CREATE TABLE IF NOT EXISTS `dutch_frontiers_blog`.`Posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Posts_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `dutch_frontiers_blog`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutch_frontiers_blog`.`Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutch_frontiers_blog`.`Details` ;

CREATE TABLE IF NOT EXISTS `dutch_frontiers_blog`.`Details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sequence` INT NULL,
  `text` LONGTEXT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Details_Posts_idx` (`Posts_id` ASC),
  CONSTRAINT `fk_Details_Posts`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `dutch_frontiers_blog`.`Posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutch_frontiers_blog`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutch_frontiers_blog`.`Comments` ;

CREATE TABLE IF NOT EXISTS `dutch_frontiers_blog`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `Users_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_Users1_idx` (`Users_id` ASC),
  INDEX `fk_Comments_Posts1_idx` (`Posts_id` ASC),
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `dutch_frontiers_blog`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `dutch_frontiers_blog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dutch_frontiers_blog`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `dutch_frontiers_blog`;
INSERT INTO `dutch_frontiers_blog`.`Users` (`id`, `name`, `email`, `date`, `active`) VALUES (1, 'Admin', 'admin@dutchfrontiers.local', '2015-02-15 21:27:52', 1);

COMMIT;

